import React, { useState, useRef, useEffect } from 'react';
import { X, Send, Sparkles, Bot } from 'lucide-react';
import { callGroq } from '../../services/groq/client';
import { AppView } from '../../types';
import { getUserTier, consumeToken, type SubscriptionTier } from '../../services/subscriptionService';
import PaywallSheet from '../PaywallSheet';

interface ChatMessage {
    id: string;
    role: 'user' | 'assistant';
    text: string;
    timestamp: number;
}

interface SkillAiChatOverlayProps {
    isOpen: boolean;
    onClose: () => void;
    skillTitle: string;
    contextText?: string;
}

export const SkillAiChatOverlay: React.FC<SkillAiChatOverlayProps> = ({
    isOpen,
    onClose,
    skillTitle,
    contextText = ''
}) => {
    const [messages, setMessages] = useState<ChatMessage[]>([]);
    const [input, setInput] = useState('');
    const [isLoading, setIsLoading] = useState(false);
    const chatEndRef = useRef<HTMLDivElement>(null);
    const inputRef = useRef<HTMLInputElement>(null);

    const [tier, setTier] = useState<SubscriptionTier | null>(null);
    const [isPaywallOpen, setIsPaywallOpen] = useState(false);
    const [paywallReason, setPaywallReason] = useState('');

    useEffect(() => {
        let isMounted = true;
        getUserTier().then(t => {
            if (isMounted) setTier(t);
        });
        return () => { isMounted = false; };
    }, []);

    // Initial greeting
    useEffect(() => {
        if (isOpen && messages.length === 0) {
            setMessages([
                {
                    id: Date.now().toString(),
                    role: 'assistant',
                    text: `Hi! I'm ready to help you with **${skillTitle}**. What's confusing you?`,
                    timestamp: Date.now()
                }
            ]);
            setTimeout(() => inputRef.current?.focus(), 300);
        }
    }, [isOpen, skillTitle, messages.length]);

    // Scroll to bottom
    useEffect(() => {
        if (isOpen && chatEndRef.current) {
            chatEndRef.current.scrollIntoView({ behavior: 'smooth' });
        }
    }, [messages, isOpen, isLoading]);

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!input.trim() || isLoading) return;

        const userText = input.trim();
        setInput('');

        // 1) Consume token
        const tokenCheck = await consumeToken('ai_chat', { strict: true });
        if (!tokenCheck.allowed) {
            setPaywallReason('Token AI harian habis. Upgrade untuk lebih banyak token!');
            setIsPaywallOpen(true);
            return;
        }

        const newUserMsg: ChatMessage = {
            id: Date.now().toString(),
            role: 'user',
            text: userText,
            timestamp: Date.now()
        };

        setMessages(prev => [...prev, newUserMsg]);
        setIsLoading(true);

        try {
            const systemPrompt = `You are a helpful, expert English tutor specifically assisting a student with the TOEFL skill: "${skillTitle}".
Keep your answers very extremely concise, friendly, and easy to understand for an intermediate English learner. Use formatting like bolding to make it readable.
If relevant context is provided, you can refer to it:
"""
${contextText.substring(0, 1500)}
"""`;

            const conversationHistory = messages.map(m => ({
                role: m.role,
                content: m.text
            }));

            const groqMessages = [
                { role: 'system', content: systemPrompt },
                ...conversationHistory,
                { role: 'user', content: userText }
            ];

            const response = await callGroq(groqMessages, 0.7);

            // Remove <think> tags often generated by reasoning models
            const cleanResponse = response.replace(/<think>[\s\S]*?<\/think>/gi, '').trim();

            const newAssistantMsg: ChatMessage = {
                id: Date.now().toString(),
                role: 'assistant',
                text: cleanResponse,
                timestamp: Date.now()
            };

            setMessages(prev => [...prev, newAssistantMsg]);
        } catch (error) {
            console.error("Chat error:", error);
            setMessages(prev => [...prev, {
                id: Date.now().toString(),
                role: 'assistant',
                text: "Sorry, I'm having trouble connecting right now. Please try asking again.",
                timestamp: Date.now()
            }]);
        } finally {
            setIsLoading(false);
        }
    };

    if (!isOpen) return null;

    // Fast fail for free tier before they even chat
    if (tier === 'free') {
        return (
            <div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center bg-slate-900/60 backdrop-blur-sm animate-in fade-in duration-300">
                <PaywallSheet
                    isOpen={true}
                    onClose={onClose}
                    triggeredBy="ai_chat"
                />
            </div>
        );
    }

    return (
        <div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center bg-slate-900/60 backdrop-blur-sm animate-in fade-in duration-300">
            <div className="w-full max-w-md h-[90vh] sm:h-[80vh] bg-white rounded-t-3xl sm:rounded-3xl flex flex-col overflow-hidden shadow-2xl animate-in slide-in-from-bottom-full sm:zoom-in-95 duration-300">
                {/* Header */}
                <div className="flex items-center justify-between px-6 py-4 border-b border-slate-100 bg-white">
                    <div className="flex items-center gap-3">
                        <div className="w-10 h-10 rounded-full bg-[#0B132B] flex items-center justify-center text-white shadow-md shadow-blue-900/20">
                            <Sparkles className="w-5 h-5 text-blue-300" />
                        </div>
                        <div>
                            <h3 className="font-bold text-slate-900 text-base leading-tight">Ask AI</h3>
                            <p className="text-[11px] text-slate-500 font-medium tracking-wide uppercase">{skillTitle}</p>
                        </div>
                    </div>
                    <button
                        onClick={onClose}
                        className="w-8 h-8 flex items-center justify-center rounded-full hover:bg-slate-100 active:bg-slate-200 transition-colors"
                    >
                        <X className="w-5 h-5 text-slate-500" />
                    </button>
                </div>

                {/* Chat Area */}
                <div className="flex-1 overflow-y-auto p-5 space-y-5 bg-slate-50/50">
                    {messages.map((msg) => (
                        <div key={msg.id} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                            {msg.role === 'assistant' && (
                                <div className="w-7 h-7 rounded-full bg-blue-100 flex items-center justify-center shrink-0 mr-2 mt-1">
                                    <Bot className="w-4 h-4 text-blue-600" />
                                </div>
                            )}
                            <div className={`max-w-[75%] rounded-2xl p-3.5 shadow-sm ${msg.role === 'user'
                                ? 'bg-[#0B132B] text-white rounded-tr-none'
                                : 'bg-white border border-slate-100 text-slate-700 rounded-tl-none'
                                }`}>
                                <div
                                    className={`text-[15px] leading-relaxed font-sans prose prose-sm max-w-none ${msg.role === 'user' ? 'prose-invert' : 'prose-slate'}`}
                                    dangerouslySetInnerHTML={{
                                        __html: msg.text
                                            .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
                                            .replace(/\*(.*?)\*/g, '<em>$1</em>')
                                            .replace(/\n/g, '<br />')
                                    }}
                                />
                                <span className={`text-[10px] block mt-1.5 ${msg.role === 'user' ? 'text-white/60 text-right' : 'text-slate-400'}`}>
                                    {new Date(msg.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                                </span>
                            </div>
                        </div>
                    ))}
                    {isLoading && (
                        <div className="flex justify-start">
                            <div className="w-7 h-7 rounded-full bg-blue-100 flex items-center justify-center shrink-0 mr-2 mt-1">
                                <Bot className="w-4 h-4 text-blue-600" />
                            </div>
                            <div className="bg-white border border-slate-100 p-4 rounded-2xl rounded-tl-none shadow-sm flex items-center gap-1.5 h-12">
                                <span className="w-1.5 h-1.5 bg-blue-400 rounded-full animate-bounce"></span>
                                <span className="w-1.5 h-1.5 bg-blue-400 rounded-full animate-bounce" style={{ animationDelay: '0.15s' }}></span>
                                <span className="w-1.5 h-1.5 bg-blue-400 rounded-full animate-bounce" style={{ animationDelay: '0.3s' }}></span>
                            </div>
                        </div>
                    )}
                    <div ref={chatEndRef} />
                </div>

                {/* Input Area */}
                <div className="p-4 bg-white border-t border-slate-100">
                    <form onSubmit={handleSubmit} className="flex items-end gap-2 relative">
                        <textarea
                            value={input}
                            onChange={(e) => setInput(e.target.value)}
                            onKeyDown={(e) => {
                                if (e.key === 'Enter' && !e.shiftKey) {
                                    e.preventDefault();
                                    handleSubmit(e);
                                }
                            }}
                            placeholder="Ask a question..."
                            className="flex-1 max-h-32 min-h-[50px] px-4 py-3.5 rounded-2xl border border-slate-200 bg-slate-50 focus:bg-white focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 transition-all resize-none text-[15px]"
                            disabled={isLoading}
                            rows={1}
                        />
                        <button
                            type="submit"
                            disabled={!input.trim() || isLoading}
                            className="w-12 h-[50px] shrink-0 rounded-2xl bg-blue-600 hover:bg-blue-700 disabled:bg-slate-200 disabled:text-slate-400 text-white flex items-center justify-center transition-colors shadow-md shadow-blue-500/20 disabled:shadow-none"
                        >
                            <Send className="w-5 h-5 ml-1" />
                        </button>
                    </form>
                    <p className="text-center text-[10px] text-slate-400 mt-3 font-medium">
                        {tier === 'c2' ? 'AI Chat Unlimited (Fair use: 5000 tokens/day).' : 'AI can make mistakes. Consider verifying important information.'}
                    </p>
                </div>
            </div>

            {/* Token Limit Paywall (Basic tier running out of tokens) */}
            <PaywallSheet
                isOpen={isPaywallOpen}
                onClose={() => setIsPaywallOpen(false)}
                triggeredBy="ai_chat"
                reason={paywallReason}
            />
        </div>
    );
};
